### ISSUE TITLE
Possible error in SIR Model

### ISSUE THREAD

**Issue by carloclaudio** [albertomercurio/covid-19_italy#3]
Buongiorno Alberto,
sto effettuando alcuni studi sui modelli matematici che simulano l'evoluzione del covid.
Nel tuo codice, mi trovo che nel calcolo del fit del modello SIR, vengono passati i dati della colonna
"totale casi", invece dovrebbero essere passati quelli della colonna "totale positivi".
Ovvero:
Popolazione = S+I+R
In questo caso stiamo trascurando i recovered, che dovrebbero essere pari ai guariti + i decessi.
Pertanto le equazioni differenziali non vengono rispettate.
Ti torna?
Grazie dell'attenzione

**Comment by albertomercurio** [comment]
Ciao carloclaudio,
il "totale positivi" corrisponderebbe alla classe "I" del S.I.R. Model. Mentre i "dimessi_guariti" più "deceduti" darebbe la classe "R". Se noti bene, dentro la funzione sir che ho scritto considero la somma I+R, che è appunto la somma delle tre cassi sopra menzionate, nonché i "totale positivi".
Spero di essere stato chiaro.

**Comment by carloclaudio** [comment]
Ciao Alberto,
siamo daccordo che:

totale_casi = deceduti+dimessi_guariti+totale_positivi

in genere nel modollo SIR la funzione matematica che si cerca di rappresentare è la I(t), mi sembra di capire dal tuo discorso che invece l'hai riscritta facendo ritornare la somma di I(t)+R(t), che è uguale al "totale_casi", ovvero S(t)-Popolazione.
E' così?
Il modo in cui l'hai scritta non mi risulta di immediata comprensione, quello che uso io è la versione classica:
https://github.com/carloclaudio/covid_italy
I parametri dell'equazione sono beta,gamma,I0,R0,S0.
Nella tua versione cosa rappresenterebbero a1 e a2?
Ciao e grazie.

**Comment by albertomercurio** [comment]
a1 e a2 sono delle costanti introdotte da una modifica del SIR Model il cui lavoro è linkato nel Readme, ma che ti linko anche qui:
https://www.sciencedirect.com/science/article/pii/S0960077920301636

Per questo il metodo SIR model non sembra di immediata comprensione, perché è modificato.
